name: Publish DL dev image

on:
  push:
    tags:
      - orbyter-dl-dev-[0-9].*

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/orbyter-dl-dev-}" >> $GITHUB_OUTPUT

      - name: Echo version
        id: echo_version
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: orbyter-dl-dev
          push: true
          tags: |
            manifoldai/orbyter-dl-dev:latest
            manifoldai/orbyter-dl-dev:${{ steps.get_version.outputs.VERSION }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: manifoldai/orbyter-dl-dev
          readme-filepath: ./orbyter-dl-dev/OVERVIEW.md
          short-description: "Machine learning development in Python with GPU support"
