name: Publish Docker image
on:
  push:
    tags:
      - orbyter-spark-dev-[0-9].*
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/orbyter-spark-dev-}
      - name: Echo version
        id: echo_version
        run: echo ${{ steps.get_version.outputs.VERSION }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: orbyter-spark-dev
          push: true
          tags: |
            manifoldai/orbyter-spark-dev:latest
            manifoldai/orbyter-spark-dev:${{ steps.get_version.outputs.VERSION }}
